### ISSUE TITLE
TcoMessenger 

### ISSUE THREAD

**Issue by TomKovac** [Inxton/TcOpen#12]
- [x] Implementation of message ```Posters``` in TcoMessenger
- [x] Unit tests of ```Posters``` of TcoMessenger
- [x] ```TcoObject``` must implement ```TcoMessenger```
- [x] ```TcoMessenger``` collected into enumerable collection
- [x] ```TcoMessenger``` performance testing
- [x] ```TcoMessenger``` and related API docu
- [x] More performance testing will be needed.

**Comment by PTKu** [comment]
On hold by #19

**Comment by Inxton-Dev** [comment]
moved to https://github.com/TcOpenGroup/TcOpen
