### ISSUE TITLE
Affect the move of element using state machine steps

### ISSUE THREAD

**Issue by GISED-Link** [Inxton/TcOpen#20]
# Open

I need your opinion for the coding style.

At the bottom of the code convention file, we can see this code (which use fluent programing):
```
// Simple example of state driven by return values from components. Piston return true when _work or _home position sensor are reached respectively.
 CASE state OF
 0:
    IF(verticalPiston.MoveToHome().Done
    AND_THEN horizontalPiston.MoveToHome().Done
    AND_THEN gripper.MoveToHome().Done)
    )
    THEN
        state := state + 1;
    END_IF;
 1:
    IF(horizontalPiston.MoveToWork().Done) THEN
        state := state + 1;
    END_IF;
 // some other cases
END_CASE
```

the AND_THEN evaluation:
https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/2528923787.html&id=

If I am correct, at step 0, we move first verticalPiston, when this move is done (and only at this point), we move the horizontalPiston, and finally we move the griper.

This code looks good to me and is really easy to understand. But I always learned that we should perform actions by using the step of the state machine, like that: 
```
// A 
 CASE state OF
 0:
    IF (verticalPiston.AtWorkPos)
    THEN
        state := state + 1;
    END_IF;
 1:
    IF (horizontalPiston.AtHomePos)
    THEN
        state := state + 1;
    END_IF;
 // some other cases

END_CASE

(* affect element *)
verticalPiston.xMoveToWork:=(state>=0 AND state<=2);
verticalPiston.xMoveToHome:=NOT verticalPiston.xMoveToWork; // May not be necessary for monostable valve
horizontalPiston.xMoveToWork:=(1=state OR 2=state);
horizontalPiston.xMoveToHome:=NOT horizontalPiston.xMoveToWork; // May not be necessary for monostable valve
// some other element

(* execute the FB, should be done with the input parameters above but it is easier for me to do things like that for this issue *)
verticalPiston();
horizontalPiston();
```

The goal is to be sure that we know the state of each element (in this case, cylinder) at each step. 

The first code is harder to create for beginners but have less lines. The second is more portable accros plateform (like sie****) since it doesn't required any extension of the IEC 61131-3.

What do you think? Is there a 3rd solution to this problem?

Here are some other example(s) from the net:
https://stefanhenneken.net/2018/11/17/iec-61131-3-the-state-pattern/

**Comment by PTKu** [comment]
As per coding style, I generally consider **readability** (can the others read the code, will I be able to read it a year from now), **scalability** (cost of changes, possibility of online change), **ease of use**, **observability** (both within development environment and in production SCADA/HMI/UI) **perfomance** (does it affect performance, and if how much). 

I vaguely recall the first example (AND_THEN), and your understanding is correct, I guess it is my piece of code, but I would not argue that's an example of best practice. It is true that the best approach is to have as little actions in a single state as possible. In the production code, I would probably put each movement in a single state. This is also good for step-by-step operations (during commissioning process) when you have an implementation of manual execution of states.

Anyway in reality sometimes you may need to speed up the process by taking multiple actions in a single state (e.g. reduction of cycle time).

As per portability the aim of this project is not to create portable code to platforms like siemens or ab. We are not willing to accept the constraints of those platforms. The aim here is to have an OOP-based framework.

Stefan's example of the state pattern is interesting, it is very neat. It is great to use it when the requirements are well defined. I guess you will see similar implementation in some components (cylinders, drives, robots etc.) in this project as well. We would like to hide implementation complexity into a set of components that can be then used in higher-level state-machine.

I don't know if I did answer your question. I am not trying to be too dogmatic about style, many times it is a matter of personal preference. In my opinion, the program should be telling a story that is easy to read :). That's more-less my attitude :)

**Comment by GISED-Link** [comment]
Thank you very much for the answer. It is exactly the kind of answer I expected. At this point I have nothing to add to this discussion 😃 

I will try as much as I can to contribute to this project. I need to be more confident with the interfaces, abstract classes, and fluent programing.

**Comment by PTKu** [comment]
Thanks @GISED-Link! Contributions are very much welcomed. We are in the early stages, laying out the foundations. My hope is to be ready with that by the end of April. We will try to bring more documentation for the contributors. The questions are also important it helps me (us) to articulate better the thoughts. So thank you for this question as well!
