### ISSUE TITLE
method ToString and Equals for each FB

### ISSUE THREAD

**Issue by GISED-Link** [Inxton/TcOpen#34]
Hi,

Should this kind of issue be reported in the forked repo (TcOpenGroup/TcOpen) or here? It is not really clear...

**Is your feature request related to a problem? Please describe.**
In my code, it gives times that I need to compare 2 FBs together. Since we are in POO, it might be that an object is equal to another even if there are diffrent instances.
I also like to have, in my HMI, the to_string represantation of the reference of the FB. Ex: My mover have a ref to FB_PieceHolder, a ref to FB_MoverAxis, a ref to FB_Station and a ref to FB_Process. When I select a Mover on my HMI, I would display which reference is currently in use by this mover. By calling MyMover.MyPieceHolder.ToString(), it will return the string made from MyMover.MyPieceHolder. Really nice and really usefull.

Maybe we can include more standard method (like the standard object class method in c#)...

**Describe the solution you'd like**
Create or add those method in the TcoObject.TcPOU Abstract FB
For the .Equals, see "addition context"
For the ToString method, I have tried:
- using var := __VARINFO(THIS^); ToString := var.System; // Generate error since __VARINFO is not possible on THIS statement
- using attribute {instance-path} on a local variable _sToStringVar but it does not exactly what I will do
- Passing a string in FB_init wich will be used by the ToString method. Not really convinient but the best solution I found until now...
- Create a _iInstanceCounter in the VAR_STAT region of the FB that incremant on each FB_Init call, and then: ToString := CONCAT('FB_Name', TO_STRING(_iInstanceCounter)). This is okay when we don't dynamically create and delete object ...

**Describe alternatives you've considered**
Add it in the interface... But since those method can be overloaded by the subclass, they really should take place in the abstract class.

**Additional context**
see here for more detail of the implemtation
https://docs.microsoft.com/en-us/dotnet/api/system.object?view=net-5.0
Also my discussion around the Equals method (look a bit under):
https://github.com/Barteling/STweep/issues/38
Also take a look of the implementation of a Equals method here (use the search and write: METHOD PUBLIC AssertEquals)
https://github.com/tcunit/TcUnit/blob/master/TcUnit/TcUnit/POUs/FB_TestSuite.TcPOU

And I would like to join the slack chanel... but I am not a member of the group so I cannot join ...

**Comment by PTKu** [comment]
Hi @GISED-Link it is OK reporting here... we PR all here to TcOpenGroup  later.

**Equals(ITcoObject)**

```TcoObject``` contains ```_identity``` which is the address of that object assigned at construction ```FB_init```. That should be unique for each instance. 

TcoObject
https://github.com/Inxton/TcOpen/blob/492b74095c07195d2958b25f17b7e204e1b6d2ff/src/TcoCore/src/XaeTcoCore/TcoCore/POUs/Prototypes/TcoObject/TcoObject.TcPOU#L111

ITcoObject
https://github.com/Inxton/TcOpen/blob/492b74095c07195d2958b25f17b7e204e1b6d2ff/src/TcoCore/src/XaeTcoCore/TcoCore/POUs/Prototypes/TcoObject/ITcoObject.TcIO#L13

I guess we can use that to implement the equality method.

@TomKovac could you have a look at that plz? This looks like useful idea...

**ToString()**

it looks a bit trickier, we could have constant string with type name, that should also include namespace and maybe be even library id... (we could get into troubles with type names in dependencies  on larger projects) What I see as a bit of trouble is that we will need to maintain that type id string when refactoring... that may lead to inconsistencies.

I would like to investigate if we can workaround _VARINFO(THIS^) issue. @TomKovac will we check that? 




Will contact Dustin about slack channel...

**Comment by GISED-Link** [comment]
@PTKu I'm not OK with your thinking about the Equals method. Imagine I have a FB_Pos2D which contains a X and a Y position. Only comparing if 2 instances are the same is not enough because I really want to know if X and Y coordinate are equal or not. We can overload each Equals method to compare the content, but in my opinion this should be done by default in the abstract class (and in this case, ignore the _identity).

By the way, why is _identity used for? Since we can get this value by using THIS or ADR(my_instance_of_FB)? I already have implemented a method called Equals which do:
```
METHOD Equals : BOOL
VAR_INPUT
    object : POINTER TO FB_SameFB_Type;
END_VAR
// code section
Equals := FALSE;

IF object <> 0 THEN
    Equals := THIS = object;
END_IF
```

And that works perfectly... It just don't check the content but in my case this is not needed, yet.

About the ToString, it is really tricky... but it shouldn't. The best way will be that Beckhoff (or Codesys) do something with its compiler and provide a built-in method, like it is the case for Enum when we add the {Attribute to_string} decorator.

**Comment by PTKu** [comment]
@GISED-Link sorry I missed you point...

Comparing content needs method override as you say. The input parameter will need to be ```ITcoObject```. Then for the comparison we will need to cast that object to appropriate interface for the comparison (should work, not sure, I will check it over the weekend). 

```_identity``` is there to track objects on the higher level applications.

**Comment by PTKu** [comment]
@GISED-Link something like this?

**TcoObject.Equals override**  
~~~
FUNCTION_BLOCK TcoObjectEqualsTest EXTENDS TcoCore.TcoObject 
VAR
	_SomeNumber : INT;
	_SomeString : STRING;	
END_VAR
//---------------------------------------------------------
METHOD PUBLIC Equals : BOOL
VAR_INPUT
	Object : ITcoObject;
END_VAR

VAR
	_object : POINTER TO TcoObjectEqualsTest;
END_VAR
//----------------------------------------------------------

IF(__QUERYPOINTER(Object,  _object)) THEN
	Equals := _object^._SomeNumber = THIS^._SomeNumber AND _object^._SomeString = THIS^._SomeString;
END_IF;	
~~~


default implementation of ```TcoObject``` would return reference equals like result

![image](https://user-images.githubusercontent.com/61538034/114262459-54d68100-99e0-11eb-8dab-63ca82035e2b.png)

ToString() deserves more discussion. If we are to copycat .net, then ToString() in default implementation does return string representation of type. However many classes have their own override of ToString() returning something different than type. I would rather implement GetType() method for getting information about the type... what's your take on that... 
I guess there will be workarround the __VARINFO issue, I will check that next week.

**Comment by PTKu** [comment]
@GISED-Link with ```ToString()```/```GetType``` thing I am out of ideas at this point. I did try several things with no success. Let's keep this open for the moment I will ask around about other options. I would rather not take the path of passing parameters at construction or anything one must do manually to get type name.

**Comment by GISED-Link** [comment]
@PTKu I'm at the same point as you... I've trying one or two more things without any success. Maybe we can try to add an {attribute}... I've seen some json library that use this kind of things. Maybe it can only be used by Tcom object written in c++...

For the Equals method, it seems ok. I still  don't really understand why the attribute _instance is prefered than THIS, but it is ok

**Comment by PTKu** [comment]
Implementation of equality method in #38 
I am creating separate issue for ```GetType()/ToString()``` in #37
