### ISSUE TITLE
Add ```GetType``` method to ```TcoObject``` that will return information about the type of the object.

### ISSUE THREAD

**Issue by PTKu** [Inxton/TcOpen#37]

**Comment by GISED-Link** [comment]
Hi,

I just see that codesys has a nice builtin operator: __POUNAME()
https://help.codesys.com/webapp/_cds_operator_pouname;product=codesys;version=3.5.16.0

Maybe we just need to wait until Beckhoff import this to Twincat

**Comment by TomKovac** [comment]
Maybe in Twincat attribute 'instance-path' could be used.
[https://infosys.beckhoff.com/english.php?content=../content/1033/tc3_plc_intro/2529681547.html&id=](url)

**Comment by PTKu** [comment]
``instance-path```  gives us instance name, we were thinking about getting the type name...

**Comment by Inxton-Dev** [comment]
moved to https://github.com/TcOpenGroup/TcOpen
