### ISSUE TITLE
Refactor to comply with conventions:

### ISSUE THREAD

**Issue by PTKu** [Inxton/TcOpen#40]
https://github.com/Inxton/TcOpen.Documentation/blob/dev/articles/Conventions/Conventions.md

see also https://github.com/Inxton/TcOpen/discussions/48

**Comment by jozefchmelar** [comment]
I found some issues in `TcoSequencer/FB_init`  there're boolean properties with `b` prefix and also the name `DoEnableAutoRestore` should be start with `Is` rather than `Do`

**Comment by Inxton-Dev** [comment]
moved to https://github.com/TcOpenGroup/TcOpen
