### ISSUE TITLE
Why is Step in Sequencer protected method?

### ISSUE THREAD

**Issue by jozefchmelar** [Inxton/TcOpen#51]
# Why is Step in Sequencer protected method?

I'd prefer to use simple sequences inside a function block, rather than creating a new function block and inherit from Sequencer. (composition over inheritance) .

This way I can have components and sequencer in the same function block. In example there's the same structure used twice

```
FUNCTION_BLOCK ST_01_Automat EXTENDS TcoCore.TcoSequencer
VAR
	_components : ST_01_Components(THIS^);
END_VAR

FUNCTION_BLOCK ST_01_Ground EXTENDS TcoCore.TcoSequencer
VAR
	_components : ST_01_Components(THIS^);
	LastStepId : INT := 32767;
END_VAR
```

I'd like to have 

```
FUNCTION_BLOCK ST_01 EXTENDS TcoCore.TcoContext
VAR
	_components : ST_01_Components(THIS^);

	// Ground position sequence
	_ground : TcoSequencer(THIS^, FALSE);
	// Automat mode sequence	
	_automat : TcoSequencer(THIS^, FALSE);
---

Method Ground

if(_ground.Step(100, ... etc) then
 _components.gripper... etc
_automat.Start().
end-if
```

But Step method is protected...Why it can't be public?

**Comment by PTKu** [comment]
We want to prevent a call from outside the sequence block. This is why sequencer is abstract and you need to implement the logic in ```Main``` method. It also should take care of opening and closing the sequence... #31.

Valid point about the usage, but let's prefer safety over convenience in this instance.
