### ISSUE TITLE
TcoSequencer documentation

### ISSUE THREAD

**Issue by jozefchmelar** [Inxton/TcOpen#52]
Hello

TcoSequencer takes two input parameters, TcoContext and a bool.  Since i'm only starting with TcoOpen I had to dig a bit too much to find out that it's an input parameter for TcoSequencer.FB_init , specifically `DoEnableAutoRestore`  which is injected into state. 

What I miss is a clear explanation what this switch does. I'd like to press F12 on TcoSequencer and read about the effects of this paramater in in the <docu> tag.

**Comment by PTKu** [comment]
Have a look at this proposal: 
https://github.com/Inxton/TcOpen/issues/53
