### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by PTKu** [Inxton/TcOpen#6]
- [x] Examples using ```TcoContext``` (corleone)
- [x] Examples using ```TcoTask```
- [x] Examples using ```TcoSequencer```
- [x] Examples using ```TcoState```

**Comment by PTKu** [comment]
Corleone family example 871b619a138078fdcf28c88c8c486713f6e11bd6 explains context?!

**Comment by Inxton-Dev** [comment]
moved to https://github.com/TcOpenGroup/TcOpen
