### ISSUE TITLE
Sequencer current step public API

### ISSUE THREAD

**Issue by jozefchmelar** [Inxton/TcOpen#66]
I'd like to access the current step description. 
I want to be able to know the step ID, if it's the last step of the sequence. 

**Describe the solution you'd like**
Define a sequence 
`Ground : GroundSequence(THIS^);`
In Main method
`Ground.IsLastStep`
`Ground.CurrentStepId`
I want to be able to access them *with autocomplete*. _currentStep works, but since it's not suggested, I'm hesitant to use it. 

I'd be ok with read only properties.

**Describe alternatives you've considered**
I could add these variables into my extended fb, but imho this functionality should be supported out of the box.

**Comment by PTKu** [comment]
Sure... we need property that returns ```currentstep``` info.
